[package]
name = "uefi-services"
version = "0.2.2"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
edition = "2018"
description = "Higher-level utilities for uefi-rs"
repository = "https://github.com/rust-osdev/uefi-rs"
keywords = ["uefi", "efi"]
categories = ["embedded", "no-std", "api-bindings"]
license = "MPL-2.0"

[badges]
travis-ci = { repository = "rust-osdev/uefi-rs" }
is-it-maintained-issue-resolution = { repository = "rust-osdev/uefi-rs" }
is-it-maintained-open-issues = { repository = "rust-osdev/uefi-rs" }

[dependencies]
rlibc = "1.0.0"
x86_64 = "0.8.3"

uefi = { path = "..", features = ["alloc", "logger"] }
log = { version = "0.4.8", default-features = false }

[features]
# Enable QEMU-specific functionality
qemu = []
